"""swing context: the hitting side's pitch type

Adds `swings.context` and widens the split column on `player_baselines` and
`change_events` from 4 to 16 characters.

WHY THE WIDEN IS NOT OPTIONAL: that column already held pitch codes (FB, SL),
which fit in 4. It now also holds swing contexts on hitting rows, and
"soft_toss" is 9 characters. On Postgres a String(4) would reject the insert
outright; on SQLite VARCHAR length is not enforced, so the same bug would run
clean locally and fail only in production. Widen both, not just one.

Hand-written with batch_alter_table rather than autogenerated: autogenerate run
against Postgres emits op.alter_column, which SQLite cannot execute ("near
ALTER: syntax error"), and this has to run on both.
"""
from alembic import op
import sqlalchemy as sa

revision = "a1c7f2e9b035"
down_revision = "48bcef2a7ac1"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("swings") as b:
        b.add_column(sa.Column("context", sa.String(16), nullable=True))

    # The old index did not include context; every baseline query now filters on it.
    op.drop_index("ix_swings_player_metric_ts", table_name="swings")
    op.create_index("ix_swings_player_metric_ts", "swings",
                    ["player_id", "metric_key", "context", "ts"])

    with op.batch_alter_table("player_baselines") as b:
        b.alter_column("pitch_type", existing_type=sa.String(4),
                       type_=sa.String(16), existing_nullable=False,
                       existing_server_default="")
    with op.batch_alter_table("change_events") as b:
        b.alter_column("pitch_type", existing_type=sa.String(4),
                       type_=sa.String(16), existing_nullable=True)


def downgrade():
    # Narrowing back to String(4) would truncate or reject any hitting row written
    # since the upgrade, so drop those rows first rather than corrupt them.
    op.execute("DELETE FROM change_events WHERE length(pitch_type) > 4")
    op.execute("DELETE FROM player_baselines WHERE length(pitch_type) > 4")
    with op.batch_alter_table("change_events") as b:
        b.alter_column("pitch_type", existing_type=sa.String(16),
                       type_=sa.String(4), existing_nullable=True)
    with op.batch_alter_table("player_baselines") as b:
        b.alter_column("pitch_type", existing_type=sa.String(16),
                       type_=sa.String(4), existing_nullable=False,
                       existing_server_default="")
    op.drop_index("ix_swings_player_metric_ts", table_name="swings")
    op.create_index("ix_swings_player_metric_ts", "swings",
                    ["player_id", "metric_key", "ts"])
    with op.batch_alter_table("swings") as b:
        b.drop_column("context")
