"""baseline schema

Revision ID: b4413b1e0d33
Revises: 
Create Date: 2026-09-01 16:32:22.755995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4413b1e0d33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('source_column', sa.String(length=120), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.Float(), server_default='1', nullable=True),
    sa.Column('confirmed_by', sa.String(length=60), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'source_column', name='uq_colmap')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('class_year', sa.String(length=10), nullable=True),
    sa.Column('primary_pos', sa.String(length=12), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('is_pitcher', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('raw_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=60), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('header', sa.JSON(), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('ai_summaries',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'basis')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('set_by', sa.String(length=60), nullable=True),
    sa.Column('set_on', sa.Date(), nullable=True),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('raw_name', sa.String(length=120), nullable=False),
    sa.Column('suggested_player_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=True),
    sa.Column('resolved_by', sa.String(length=60), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['raw_imports.id'], ),
    sa.ForeignKeyConstraint(['suggested_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'alias', name='uq_alias_source')
    )
    op.create_table('player_baselines',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('pitch_type', sa.String(length=4), server_default='', nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('sd', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'metric_key', 'pitch_type', 'window_end')
    )
    op.create_table('player_links',
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('player_links', schema=None) as batch_op:
        batch_op.create_index('ix_player_link_player', ['player_id'], unique=False)

    op.create_table('player_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('jersey', sa.String(length=4), nullable=True),
    sa.Column('position', sa.String(length=24), nullable=True),
    sa.Column('academic_year', sa.String(length=12), nullable=True),
    sa.Column('height_in', sa.Integer(), nullable=True),
    sa.Column('is_pitcher', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('source', sa.String(length=20), server_default='roster_site', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season')
    )
    with op.batch_alter_table('player_seasons', schema=None) as batch_op:
        batch_op.create_index('ix_player_seasons_season_level', ['season', 'level'], unique=False)

    op.create_table('player_vendor_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'vendor_id', name='uq_vendor_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['raw_imports.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_ref', name='uq_session_source_ref')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_player_date', ['player_id', 'session_date'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('intervention_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('coach', sa.String(length=60), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=16), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('pitch_type', sa.String(length=4), nullable=True),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitch_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_pitch_player_metric_ts', ['player_id', 'metric_key', 'ts'], unique=False)
        batch_op.create_index('ix_pitch_session', ['session_id'], unique=False)

    op.create_table('swings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swings', schema=None) as batch_op:
        batch_op.create_index('ix_swings_player_metric_ts', ['player_id', 'metric_key', 'ts'], unique=False)
        batch_op.create_index('ix_swings_session', ['session_id'], unique=False)

    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('pitch_type', sa.String(length=4), nullable=True),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('recent_mean', sa.Float(), nullable=True),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('favorable', sa.Boolean(), nullable=True),
    sa.Column('n_recent', sa.Integer(), nullable=True),
    sa.Column('n_baseline', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index('ix_change_player', ['player_id', 'detected_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index('ix_change_player')

    op.drop_table('change_events')
    with op.batch_alter_table('swings', schema=None) as batch_op:
        batch_op.drop_index('ix_swings_session')
        batch_op.drop_index('ix_swings_player_metric_ts')

    op.drop_table('swings')
    with op.batch_alter_table('pitch_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_pitch_session')
        batch_op.drop_index('ix_pitch_player_metric_ts')

    op.drop_table('pitch_metrics')
    op.drop_table('interventions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_player_date')

    op.drop_table('sessions')
    op.drop_table('player_vendor_ids')
    with op.batch_alter_table('player_seasons', schema=None) as batch_op:
        batch_op.drop_index('ix_player_seasons_season_level')

    op.drop_table('player_seasons')
    with op.batch_alter_table('player_links', schema=None) as batch_op:
        batch_op.drop_index('ix_player_link_player')

    op.drop_table('player_links')
    op.drop_table('player_baselines')
    op.drop_table('player_aliases')
    op.drop_table('name_review')
    op.drop_table('goals')
    op.drop_table('ai_summaries')
    op.drop_table('raw_imports')
    op.drop_table('players')
    op.drop_table('column_maps')
    # ### end Alembic commands ###
